"""add weather_tone to settings

Revision ID: 7960ff215c9f
Revises: a1b2c3d4e5f6
Create Date: 2026-07-27 18:29:57.582530

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7960ff215c9f'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_records', schema=None) as batch_op:
        batch_op.alter_column('items',
               existing_type=sa.TEXT(),
               type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
               existing_nullable=True)

    with op.batch_alter_table('ocr_cache', schema=None) as batch_op:
        batch_op.alter_column('parsed',
               existing_type=sa.TEXT(),
               type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
               existing_nullable=True)

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.alter_column('identity',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               nullable=False,
               existing_server_default=sa.text("'worker'"))
        batch_op.alter_column('routine_start',
               existing_type=sa.TEXT(),
               type_=sa.String(length=8),
               nullable=False,
               existing_server_default=sa.text("'09:00'"))
        batch_op.alter_column('routine_end',
               existing_type=sa.TEXT(),
               type_=sa.String(length=8),
               nullable=False,
               existing_server_default=sa.text("'18:00'"))
        batch_op.alter_column('focus_area',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('wants_fitness',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('fitness_mode',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               nullable=False,
               existing_server_default=sa.text("'self'"))

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weather_tone', sa.Text(), nullable=True))

    with op.batch_alter_table('user_patterns', schema=None) as batch_op:
        batch_op.alter_column('pattern_value',
               existing_type=sa.TEXT(),
               type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_patterns', schema=None) as batch_op:
        batch_op.alter_column('pattern_value',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('weather_tone')

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.alter_column('fitness_mode',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'self'"))
        batch_op.alter_column('wants_fitness',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('focus_area',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('routine_end',
               existing_type=sa.String(length=8),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'18:00'"))
        batch_op.alter_column('routine_start',
               existing_type=sa.String(length=8),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'09:00'"))
        batch_op.alter_column('identity',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'worker'"))

    with op.batch_alter_table('ocr_cache', schema=None) as batch_op:
        batch_op.alter_column('parsed',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('meal_records', schema=None) as batch_op:
        batch_op.alter_column('items',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
