"""phone_auth

Revision ID: cf743d733813
Revises: 
Create Date: 2026-07-14 18:26:48.223276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf743d733813'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sms_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sms_codes_phone'), ['phone'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)

    # Fill NULL phone values for existing users using their id as a placeholder
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT id FROM users WHERE phone IS NULL"))
    for row in result:
        connection.execute(
            sa.text("UPDATE users SET phone = :phone WHERE id = :id"),
            {"phone": f"migrated_{row[0]}", "id": row[0]},
        )

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone', existing_type=sa.String(length=20), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=1)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('phone')

    with op.batch_alter_table('sms_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sms_codes_phone'))

    op.drop_table('sms_codes')
    # ### end Alembic commands ###
